OpenAPI schemas
paypal/api-standards pull request #28
Opened 2022-02-23 20:17 UTC by jayadebaj

Deprecated JSON draft-04 and added OpenAPI Schemas.

2022-02-23 22:49 UTC, mimckenna requested changes
Overall, looks good to go.  I had a few comments and input to docs and where URLs point when referring to service APIs.

Please remove [address_postal_code_validation.json](https://github.com/paypal/api-standards/pull/28/files#diff-d7db2b8ba4a0b6490a42bbfef81d0d43b27b3e3d7db5792b67a04bd0fc8a1537) as it was only for the now-depracated simple address.json.

2022-02-23 22:49 UTC, mimckenna commented on v1/schema/json/openapi-2.0/orthography.json
> +    },
Please move `Kana` to be alphabetical, between `Jpan` and `Khmr`

2022-02-23 22:49 UTC, mimckenna commented on v1/schema/json/openapi-2.0/orthography.json
> +    {
Please add `Hira` for Hiragana and `Hrkt` which incudes both Hiragana and Katakana.  `Kana` only supports katakana.  We might need this for updates to the JP UX.
```
    {
        "value" : "Hira",
        "description": "Japanese Hiragana"
    },
    {
        "value" : "Hrkt",
        "description": "Japanese syllabaries (alias for Hiragana + Katakana)"
    },
```

2022-02-23 22:49 UTC, mimckenna commented on v1/schema/json/openapi-2.0/province.json
> +    "description": "The state or province information, including the [ISO 3166-2:2013](https://www.iso.org/standard/63546.html)-formatted state or province code. Useful for statistical, market region
Now `ISO 3166-2:2020` (https://www.iso.org/standard/72483.html)

2022-02-23 22:49 UTC, mimckenna commented on v1/schema/json/openapi-2.0/province.json
> +            "description": "The [state or province code](/api/rest/reference/state-codes/), as defined by [ISO 3166-2:2013](https://www.iso.org/standard/63546.html).",
Ditto
ISO 3166-2:2020 (https://www.iso.org/standard/72483.html)

2022-02-23 22:49 UTC, mimckenna commented on v1/schema/json/openapi-2.0/province.json
> +            "pattern": "^[A-Z]{2}-([A-Z]{2,3}|[0-9]{2,3})$"
Note: this information can also be found in CLDR (Common Locale Data Repository) in the [territory_subdivisions data](https://unicode-org.github.io/cldr-staging/charts/latest/supplemental/territory_subdivisions.html)

2022-02-23 22:49 UTC, mimckenna commented on v1/schema/json/openapi-2.0/province.json
> +            "description": "The Latin province name, if the local name is in non-Latin script. For example, `北京` for Beijing."
Maybe a little clearer wording would be:
> For example, if local_name is \`北京\`, the latin_name is \`Beijing\`.

2022-02-23 22:49 UTC, mimckenna commented on v1/schema/json/openapi-2.0/province.json
> +    "description": "The state or province information, including the [ISO 3166-2:2013](https://www.iso.org/standard/63546.html)-formatted state or province code. Useful for statistical, market region
Also note: many countries do NOT use province codes in their postal addresses, e.g. Belgium and Germany, but the ISO 3166-2 codes are used for market and payment regions.

2022-02-23 22:49 UTC, mimckenna commented on v1/schema/json/openapi-2.0/time_duration.json
> +    "description": "The [ISO-8601-formatted](https://www.iso.org/standard/40874.html) length of time in years, months, weeks, days, hours, minutes, and seconds.<blockquote><strong>Note:</strong> The
Also note that duration in months may vary depending on the start date used since months may contain from 28 to 31 days.

2022-02-23 23:21 UTC, jayadebaj commented on v1/schema/json/openapi-2.0/address_postal_code_validation.json
> +{
Good Catch. Deleted.

2022-02-23 23:40 UTC, jayadebaj commented on v1/schema/json/openapi-2.0/error.json
> +            "description": "An array of request-related [HATEOAS links](/api/rest/responses/#hateoas-links).",
done. This is a external dev portal relative URI. We can remove it instead

2022-02-23 23:43 UTC, jayadebaj commented on v1/schema/json/openapi-2.0/full_name.json
> +    "description": "The full name of the party, for example, the name of a cardholder.",
done

2022-02-23 23:52 UTC, jayadebaj commented on v1/schema/json/openapi-2.0/link_description.json
> +    "description": "The request-related [HATEOAS link](/api/rest/responses/#hateoas-links) information.",
yes corrected to external dev portal link

2022-02-23 23:54 UTC, jayadebaj commented on v1/schema/json/openapi-2.0/province.json
> +    "description": "The state or province information, including the [ISO 3166-2:2013](https://www.iso.org/standard/63546.html)-formatted state or province code. Useful for statistical, market region
done thanks

2022-02-24 00:58 UTC, jayadebaj commented on v1/schema/json/openapi-2.0/orthography.json
> +    },
Good suggestion. updated.

2022-02-24 01:06 UTC, jayadebaj commented on v1/schema/json/openapi-2.0/orthography.json
> +    {
done

2022-02-24 01:42 UTC, mimckenna commented on v1/schema/json/openapi-2.0/language.json
> +    "pattern": "^[a-z]{2}(?:-[A-Z][a-z]{3})?(?:-(?:[A-Z]{2}))?$"
We can catch this with v5 ...

2022-02-24 01:48 UTC, mimckenna approved these changes
Updates and changes look good 👍

2022-02-24 01:50 UTC, merged

2022-02-24 01:56 UTC, mimckenna reviewed
Minor URL fix in province.json

2022-02-24 01:56 UTC, mimckenna commented on v1/schema/json/openapi-2.0/province.json
> +            "description": "The [state or province code](/api/rest/reference/state-codes/), as defined by [ISO 3166-2:2020](https://www.iso.org/standard/72483.html).",
Another URL to fix ...